command_timeout = 3000
add_newline = false

[directory.substitutions]
'rosemary/src/Web/accuRx.Web.Design/' = '[accurx-design] '
'rosemary/src/Web/accuRx.Web.Design' = '[accurx-design]'
'rosemary/src/Web/accuRx.Web.Client.Shared/' = '[accurx-shared] '
'rosemary/src/Web/accuRx.Web.Client.Shared' = '[accurx-shared]'
'rosemary/src/Web/accuRx.Fleming.Client/ClientApp/' = '[fleming-client] '
'rosemary/src/Web/accuRx.Fleming.Client/ClientApp' = '[fleming-client]'
'rosemary/src/Web/accuRx.Florey.Client/ClientApp/' = '[florey-client] '
'rosemary/src/Web/accuRx.Florey.Client/ClientApp' = '[florey-client]'
'rosemary/src/Web/accuRx.PatientPortal.Client/ClientApp/' = '[patient-portal] '
'rosemary/src/Web/accuRx.PatientPortal.Client/ClientApp' = '[patient-portal]'
'rosemary/' = 'rosemary '
'rosemary' = '[rosemary]'

[cmd_duration]
disabled = true

[time]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[nodejs]
symbol = "îœ˜ "
format = '[$symbol]($style)'
disabled = true

[python]
symbol = "îˆµ "
format = '[$symbol]($style)'
disabled = true

[git_branch]
symbol = "ï˜"
format = '[$symbol $branch ]($style)'

[git_status]
up_to_date = "âœ… "
ahead = "ğŸ”¼ "
behind = "ğŸ”½ "
diverged = "ğŸ”€ "
conflicted = "âŒ "
untracked = '[â€¢$count ](yellow)'
staged = '[â€¢$count ](green)'
stashed = ""
modified = '[â€¢$count ](blue)'
renamed = ""
deleted = '[â€¢$count ](red)'
style = "bright-white"
format = "$ahead_behind$untracked$modified$deleted$staged"

[character]
success_symbol = "ğŸ‘‰ğŸ»"
error_symbol = "ğŸ‘‰ğŸ»"

[line_break]
disabled = true

[package]
disabled = true
